config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :restaurants, except: [:delete, :update, :edit] do
    resources :reviews, only: [:create, :index]
    # if it flops add back :new to reviews
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # associations and validations go in the model
  # category array goes here
  # CAPITALS makes it global and can be used everywhere
  ALLOWED_CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, dependent: :destroy
  # with has_many, we can call @restaurant.review on show pages etc

  validates :name, :address, :category, presence: true
  validates :category, inclusion: ALLOWED_CATEGORIES

  # When a restaurant is destroyed, all of its reviews must be destroyed as well.
end

app/models/review.rb
class Review < ApplicationRecord
  # associations and validations go in MODEL
  belongs_to :restaurant

  validates :content, :rating, presence: true

  # A review’s rating must be a number between 0 and 5
  # A review’s rating must be an integer only
  validates :rating, inclusion: 0..5, numericality: {only_integer: true}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    # have access to @review because it belongs to restaurants
    # does it work the other way too?
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(set_restaurant)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # strong params
  def set_restaurant
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def index
    @reviews = Review.all
  end

  # def new
  #   # Have to fetch the restaurant first
  #   # https://stackoverflow.com/questions/70686373/nomethoderror-in-reviewsnew-after-clicking-on-a-link-to-create-review-page
  #   @review = Review.new
  # end

  def create
    # Need to fetch @restaurant first so @review has requisite information to add to
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      # how to render parent restaurant's 'show'
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
    # do we have to pass in restaurant id?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>  <%= link_to restaurant.name, restaurant_path(restaurant)  %> </li>
  <% end  %>
</ul>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, collection: Restaurant::ALLOWED_CATEGORIES %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<div class="container">

  <h2>Restaurant details</h2>
  <p> <%= link_to " Go back home", restaurants_path %> </p>
  <ul>
    <li><%= @restaurant.name %></li>
    <li><%= @restaurant.address %></li>
    <li><%= @restaurant.category %></li>
  </ul>


  <div>
    <h2> <%= @restaurant.name %> reviews</h2>
    <div>
      <ol>
        <% @restaurant.reviews.each do |review| %>
          <li>
            <p> <b>Review:</b> <%= review.content %> </p>
            <p> <b>Rating:</b> <%= review.rating %> / 5</p>
          </li>
        <% end %>
      </ol>
    </div>
  </div>

  <%# Add review %>
  <div>
    <h4> Add review for <%= @restaurant.name %> </h3>
    <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.submit %>
    <% end %>
  </div>

</div>

<%# <%= link_to "Add Review", new_restaurant_review_path(@restaurant, @review) %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>